# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'amplify-ios-import-bucket' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for amplify-ios-import-bucket
  pod 'Amplify'
  pod 'AmplifyPlugins/AWSS3StoragePlugin'
  pod 'AmplifyPlugins/AWSCognitoAuthPlugin'
end
