platform :ios, '14.0'

target 'amplify-datastore-storage' do

  use_frameworks!

  pod 'Amplify'

  pod 'AmplifyPlugins/AWSCognitoAuthPlugin'
  pod 'AmplifyPlugins/AWSS3StoragePlugin'

  pod 'AmplifyPlugins/AWSAPIPlugin'
  pod 'AmplifyPlugins/AWSDataStorePlugin'

end
