# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'shopping-cart' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for shopping-cart
    pod 'Amplify'
    pod 'AmplifyPlugins/AWSAPIPlugin'
    pod 'AmplifyPlugins/AWSDataStorePlugin'
end
