# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'Auth-Web-UI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Auth-Web-UI
  pod 'Amplify'
  pod 'AmplifyPlugins/AWSCognitoAuthPlugin'

end
