# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'amplify-api-realtime-chat' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for amplify-api-realtime-chat
  pod 'Amplify'
  pod 'AmplifyPlugins/AWSAPIPlugin'

end
