# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'amplify-app-ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for amplify-app-ios
  pod 'Amplify'
  pod 'AmplifyPlugins/AWSCognitoAuthPlugin'
  pod 'AmplifyPlugins/AWSPinpointAnalyticsPlugin'
  pod 'AmplifyPlugins/AWSAPIPlugin'
  pod 'AmplifyPlugins/AWSDataStorePlugin'
  pod 'AWSPredictionsPlugin'
  pod 'CoreMLPredictionsPlugin'
  pod 'AmplifyPlugins/AWSS3StoragePlugin'
end
